---
title: "Configure general environment for all markdowns"
author: "Dmitry Pavlyuk"
date: "February 6, 2019"
output: html_document
---

# Configuration
```{r setup, comment=FALSE, message = FALSE, echo=FALSE, warning=FALSE}
rm(list=ls())           # Clean the environment
options(scipen=6)       # display digits proberly!! not the scientific version
options(digits.secs=6)  # use milliseconds in Date/Time data types
library(knitr)          # set global knitr options of the document
opts_chunk$set(comment='', message = TRUE, echo=TRUE, error=TRUE, warning=TRUE)
```

```{r general_config}
# Downloaded data folder
data.folder.downloaded <- file.path(getwd(),"data","downloaded")
dir.create(data.folder.downloaded, showWarnings = FALSE)
data.folder.tmp <- file.path(getwd(),"data","tmp")
dir.create(data.folder.tmp, showWarnings = FALSE)


# Transformed data folder
data.folder.prepared <- file.path(getwd(),"data","prepared")
dir.create(data.folder.prepared, showWarnings = FALSE)

# Local config folder
config.folder <- file.path(getwd(),"data","config")
dir.create(config.folder, showWarnings = FALSE)

### Configure remote settings
download.website <- "http://www.d.umn.edu/tdrl/traffic/"

# Setup the first date for downloading
download.start.date <- as.Date("20180901", format="%Y%m%d")

# Setup number of days for downloading
download.days <- 7

# Define remote file names
download.files <- paste0(format(seq(download.start.date, by = "day", length.out = download.days),
                                format="%Y%m%d", tz = "UTC"),".traffic")

# Setup detector network config url
config.filename <- "metro_config.xml"
config.filename.gz <- paste0(config.filename,".gz")
config.url<-paste0("http://data.dot.state.mn.us/iris_xml/",config.filename.gz)
config.file.gz <- file.path(config.folder, config.filename.gz)
config.file <- file.path(config.folder, config.filename)
config.rds <- file.path(data.folder.prepared, "config.rds")
data.rds <- file.path(data.folder.prepared,"working-raw.rds")

impute.limit <- 0.2
```