---
title: "illustrations"
author: "Dmitry Pavlyuk"
date: "February 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("needs")
needs(DiagrammeR)
```


```{r graphviz}
g<-create_graph() %>%
  add_node(label= "1",node_aes=node_aes(x = 1, y=3)) %>%
  add_node(label= "2",node_aes=node_aes(x = 1, y=1)) %>%
  add_node(label= "3",node_aes=node_aes(x = 3, y=2)) %>%
  add_node(label= "4",node_aes=node_aes(x = 5, y=2)) %>%
  add_edge(from=1, to=3, edge_aes = edge_aes(label = "1 time lag"))%>%
  add_edge(from=2, to=3)%>%
  add_edge(from=3, to=4)%>%
  add_global_graph_attrs(attr = "splines",value = "spline", attr_type = "graph")%>%render_graph


g<-create_graph() %>%
  add_node(label= "...",node_aes=node_aes(color = "white", fillcolor = "white", x = 1, y=1)) %>%
  add_node(label = "!X<SUB>2</SUB>!") %>%
  add_node(label = "three") %>%
  add_node(label = "four")%>%
  set_node_position(node = 2,x = 2, y = 2) %>%
  set_node_position(node = 3,x = 3, y = 3) %>%
  set_node_position(node = 4,x = 4, y = 4) %>%
  add_edge(from=1, to=2)%>%
  add_edge(from=2, to=2)%>%
  add_edge(from=1, to=3)%>%
  add_edge(from=3, to=4)%>%
  add_global_graph_attrs(attr = "splines",value = "spline", attr_type = "graph")%>%render_graph

viz<-g$x$diagram
viz<-gsub("!\"","",(gsub("\"!","",viz)))

g$x$diagram <-viz

grViz(viz)


grViz('
digraph G {
        x11[label="<X<SUB>1</SUB><SUP>(1)</SUP>>"];   
        x21[label = <X<SUB>2</SUB><SUP>(1)</SUP>>, color = \"gray70\"];
        x11 -> x21 
    }
')

grViz('
      digraph {\n\ngraph [layout = \"neato\",\n





outputorder = \"edgesfirst\",\n       bgcolor = \"white\",\n       splines = \"spline\"]\n\nnode [fontname = \"Helvetica\",\n      fontsize = \"10\",\n      shape = \"circle\",\n      fixedsize = \"true\",\n      width = \"0.5\",\n      style = \"filled\",\n      fillcolor = \"aliceblue\",\n      color = \"gray70\",\n      fontcolor = \"gray50\"]\n\nedge [fontname = \"Helvetica\",\n     fontsize = \"8\",\n     len = \"1.5\",\n     color = \"gray80\",\n     arrowsize = \"0.5\"]\n\n  \"1\" [label = \"...\", color = \"white\", fillcolor = \"#FFFFFF\", fontcolor = \"#000000\", pos = \"1,1] \n  \"2\" [label =X<SUB>2</SUB>, color = \"gray70\", fillcolor = \"#F0F8FF\", fontcolor = \"#000000\", pos = \"2,2] \n  \"3\" [label = \"three\", color = \"gray70\", fillcolor = \"#F0F8FF\", fontcolor = \"#000000\", pos = \"3,3] \n  \"4\" [label = \"four\", color = \"gray70\", fillcolor = \"#F0F8FF\", fontcolor = \"#000000\", pos = \"4,4] \n  \"1\"->\"2\" \n  \"2\"->\"2\" \n  \"1\"->\"3\" \n  \"3\"->\"4\" \n}
      ')
```
