---
title: "Ensemble feature selection"
author: "Dmitry Pavlyuk"
date: "March 24, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

This markdown document reproduces the research "Robust learning of urban traffic flows' spatiotemporal structure" (to be submitted)


```{r child='sampling.Rmd'}
```


Load necessary libraries
----------------
```{r libs}
library(needs)
needs(knitr)
needs(tidyverse)
needs(reshape2)
needs(ggplot2)
needs(geosphere)
needs(igraph)
needs(Metrics)
needs(imputeTS)
needs(e1071)
needs(MTS)
needs(forecast)
needs(doParallel)
needs(glasso)
needs(scales)
needs(stringr)
needs(e1071 )
needs(randomForest )
needs(Boruta)
needs(ggplot2)
needs(tibbletime)
needs(tidyverse)
needs(svMisc)
needs(rlist)
needs(plot.matrix)
needs(fsMTS)

source(file.path("R","prepare_data_functions.R"))
source(file.path("R","cv_functions.R"))
source(file.path("R","cv_utils.R"))
source(file.path("R","models_util.R"))
source(file.path("R","models_baseline.R"))
source(file.path("R","models_spvar.R"))
source(file.path("R","models_spatial.R"))


# Define files for intermediate results
dir<-"TRC2020"
models.estimated.file <- file.path(dir,"models.rds")
results.file <- file.path(dir,"results.rds")
complete.rds <- file.path("data","prepared","ALL5-original.rds")
sample.rds <- file.path(dir,"data64.rds")
ta<-5
```

```{r localized_vs_global}
folder <- "C:/tmp/fs/64"
fname<-"MI"
maxsize<-4032
localized <- readRDS(file.path(folder,paste0(fname,"loc/",maxsize,"/3/2017-08-13_000000.rds")))
global <- readRDS(file.path(folder,paste0(fname,"/",maxsize,"/3/2017-08-13_000000.rds")))
cor(as.vector(localized), as.vector(global))
df.compare <- data.frame(threshold=seq(0,1,by=0.05), similarity = NA)
for (i in 1:nrow(df.compare))
  df.compare[i,"similarity"]<-fsMTS::fsSimilarity(localized, global,cutoff=T, threshold = df.compare[i,"threshold"], method = "Kuncheva")
df.compare
image(localized)
localised.folder <- file.path(folder,paste0(fname,"locg/36/3"))
global.folder <- file.path(folder,paste0(fname,"g/36/3"))
res<-NULL
for (f in list.files(localised.folder )){
  loc <- readRDS(file.path(localised.folder,f))
  glob <- readRDS(file.path(global.folder,f))
  for (thres in seq(0,1,by=0.05)){
    res<-bind_rows(res,list(filename=f,threshold=thres, 
                       similarity=fsMTS::fsSimilarity(loc, glob,cutoff=T, threshold =thres, method = "Kuncheva")))
  }
}
res <-as_tibble(res)
res<-res%>%mutate(sec=as.numeric(gsub(".rds","",filename)), time=(sec/3600))
res.gr<-res%>%arrange(time)%>%group_by(time)%>%summarise(minsimilarity=min(similarity),maxsimilarity=max(similarity))
res.gr%>%ggplot(aes(x = time, y=minsimilarity))+geom_line()

localised.folder <- file.path(folder,paste0(fname,"loc/36/3"))
global.folder <- file.path(folder,paste0(fname,"/36/3"))
res2<-NULL
for (f in list.files(localised.folder )){
  loc <- readRDS(file.path(localised.folder,f))
  glob <- readRDS(file.path(global.folder,f))
  for (thres in seq(0,1,by=0.05)){
    res2<-bind_rows(res2,list(filename=f,threshold=thres, 
                       similarity=fsMTS::fsSimilarity(loc, glob,cutoff=T, threshold =thres, method = "Kuncheva")))
  }
  print(f)
}
res2 <-as_tibble(res2)
fmt <- "%Y-%m-%d_%H%M%S"
res2<-res2%>%filter(threshold>0.0)%>%mutate(time=as.POSIXct(gsub(".rds","",filename),format=fmt, tz="GMT"))%>%mutate(dow_time=format(time,"%w %H:%M", tz="GMT"))
saveRDS(res2, file.path(dir,paste0(fname,"_localised_vs_global.rds")))

res2.gr<-res2%>%filter(threshold==0.1)%>%arrange(dow_time)%>%group_by(dow_time)%>%summarise(time=min(time),minsimilarity=min(similarity),maxsimilarity=max(similarity))
res2.gr%>%ggplot(aes(x = time, y=minsimilarity))+geom_line()
```

```{r fs_stability}


oneStepSimilarity <- function(folder, date.from,date.to, threshold, method){
  dates <- seq(from=date.from, to=date.to, by="5 min")
  res <- list()
  fs.prev<-NULL
  fmt <- "%Y-%m-%d_%H%M%S"
  for(row in 1:length(dates)){
    name<-format(dates[row],fmt)
    #filename <- paste0(name,".rds")
    filename <- file.path(paste0(wday(dates[row]),"_",daySec(dates[row]),".rds"))
    if (file.exists(file.path(folder, filename))){
      fs <- readRDS(file.path(folder, filename))
      if (!is.null(fs.prev)){
        res[[length(res)+1]] <- list(datetime=dates[row], 
                         similarity=fsMTS::fsSimilarity(fs.prev, fs,cutoff=T, 
                                                        threshold = threshold, method=method),
                         threshold = threshold,
                         method=method,
                         key=folder)
      }
      fs.prev <- fs
    }else{
      fs.prev <- NULL
    }
  }
  return(bind_rows(res))
}

folder<-RFg.folder
date.from <- as.POSIXct("2017-07-31_000000",format=fmt)
date.to <- as.POSIXct("2017-08-07_000000",format=fmt)
r<-oneStepSimilarity(folder, date.from,date.to, threshold=0.1, method="Kuncheva")
r$fs<-"RF"
r$strategy<-"daytime"
saveRDS(r, file.path(dir,"onestep","RF_daytime.rds"))
#r<-r%>%separate(file,c("wd","sec"))%>%mutate(datetime=as.POSIXct("2017-07-29",format="%Y-%m-%d")+(as.numeric(wd

res<-list()
for (f in list.files(file.path(dir,"onestep"))){
  res[[length(res)+1]]<-readRDS(file.path(dir,"onestep",f))
}
all<-bind_rows(res)
saveRDS(res, file.path(dir,"onestep","all.rds"))

res<-all%>%mutate(wd=wday(datetime))%>%filter(wd==3)%>%mutate(dow_time=format(datetime,"%H:%M"))

res%>%filter(method=="Kuncheva",fs=="RF", threshold>0)%>%mutate(key=paste(fs, strategy))%>%group_by(strategy,dow_time)%>%summarise(mean.similarity=mean(similarity),dt=first(datetime))%>%ggplot(aes(x = dt, y=mean.similarity, group=strategy, col=strategy))+geom_line(size=1)+scale_x_datetime(labels = date_format("%H:%M", tz="Europe/Helsinki"),date_breaks = "4 hours",expand = c(0,0))+ xlab("Time of the day") + ylab("One-step similarity")+ guides(col=guide_legend(title="Feature selection strategy"))+ theme(legend.position="bottom")+scale_color_brewer(palette="Dark2")

res%>%filter(method=="Kuncheva",strategy=="dynamic", threshold>0)%>%mutate(key=paste(fs, strategy))%>%group_by(fs,dow_time)%>%summarise(mean.similarity=mean(similarity),dt=first(datetime))%>%ggplot(aes(x = dt, y=mean.similarity, group=fs, col=fs))+geom_line(size=1)+scale_x_datetime(labels = date_format("%H:%M", tz="Europe/Helsinki"),date_breaks = "4 hours",expand = c(0,0))+ xlab("Time of the day") + ylab("One-step similarity")+ guides(col=guide_legend(title="Feature selection algorithm"))+ theme(legend.position="bottom")+scale_color_brewer(palette="Dark2")

res%>%group_by(fs,strategy)%>%summarise(mean.onestep=mean(similarity))%>%spread(strategy,"mean.onestep")
```
```{r}

fs <- readRDS(file.path(folder,"2017-07-31_080000.rds"))
res<-as_tibble(cutoff(fs,0.1),rownames = "lnode")%>%gather(key="node", value="value",-one_of("lnode"))%>%filter(value==1)%>%
  mutate(lag=as.numeric(substr(lnode,regexpr(".l",lnode)+2,length(lnode))),
         related_node=substr(lnode,1,regexpr(".l",lnode)-1))%>%select(node,related_node,lag)
res%>%group_by(node,lag)%>%summarise(n=n())%>%arrange(node,desc(n))%>%print(n=100)

res%>%filter(node=="rnd_95775")%>%print(n=30)
related<-res%>%filter(node=="rnd_95775")%>%select(related_node)%>%pull
write.csv(mysample$config.nodes%>%filter(node_name %in% related)%>%inner_join(res%>%filter(node=="rnd_95775"), by=c("node_name"="related_node")),file.path(dir,"nodes-lag1.csv"),  row.names = F)

```

```{r}
loadDay<-function(datetime, folder){
  fmt <- "%Y-%m-%d_%H%M%S"
  dates <- seq(from=datetime, to=datetime+(24*60-1)*60, by="5 min")
  mlist<-list()
  for(row in 1:length(dates)){
    name<-format(dates[row],fmt)
    #filename <- paste0(name,".rds")
    filename <- file.path(paste0(wday(dates[row]),"_",daySec(dates[row]),".rds"))
    if (file.exists(file.path(folder, filename))){
      fs <- readRDS(file.path(folder, filename))
      mlist[[name]]<-fs
    }
  }  
  return(mlist)
}
needs(lubridate)

fmt <- "%Y-%m-%d_%H%M%S"
date.from <- as.POSIXct("2017-07-31_000000",format=fmt)
date.to <- as.POSIXct("2017-08-06_000000",format=fmt)
days <- seq(from=date.from, to=date.to, by="1 days")
cl <- makeCluster(5, outfile="outfile.txt")
registerDoParallel(cl)
foreach (d = 1:length(days),.export=c("loadDay"),
                  .packages=c("fsMTS","dplyr","lubridate")) %dopar% {
  res<-list()
  day<-days[d]
  for (fold in c(CCFg.folder,MIg.folder,GLASSOg.folder,LARSg.folder,RFg.folder,EnsVotingg.folder,EnsRankingg.folder)){
    print(paste(day,fold))
    ml<-loadDay(day,fold)
    msim<-fsSimilarityMatrix(ml,threshold=0.1,method="Kuncheva")
    print(paste("Stability", mean(msim)))
    res[[length(res)+1]]<-list(folder=fold,date=day,stability=mean(msim))
  }
  result<-bind_rows(res)
  fmt <- "%Y-%m-%d_%H%M%S"
  filename<-paste0(format(day,fmt),".rds")
  print(filename)
  saveRDS(result, file.path("stability","daytime", filename))
}

res<-list()
for (f in list.files(file.path("stability","daytime"))){
  res[[length(res)+1]]<-readRDS(file.path("stability","daytime",f))
}
all<-bind_rows(res)
all%>%group_by(folder)%>%summarise(mean.stability = mean(stability))


plot(mlist[["EnsRanking"]], col=rev(heat.colors(10)), key=NULL, main="EnsRanking",ylab="",xlab="", axis.col = NULL, axis.row = NULL,border="lightgrey")

```

```{r ensemble_similarity}
mlist<-list(
  CCF=readRDS(CCF.global),
  GLASSO=readRDS(GLASSO.global),
  MI=readRDS(MI.global),
  LARS=readRDS(LARS.global),
  RF=readRDS(RF.global),
  Distance=readRDS(distance.folder),
  EnsVoting=readRDS(EnsVoting.global),
  EnsRanking=readRDS(EnsRanking.global)
)
plot(mlist[["EnsRanking"]], col=rev(heat.colors(10)), key=NULL, main="EnsRanking",ylab="",xlab="", axis.col = NULL, axis.row = NULL,border="lightgrey")
plot(mlist[["EnsVoting"]], col=rev(heat.colors(10)), key=NULL, main="EnsVoting",ylab="",xlab="", axis.col = NULL, axis.row = NULL,border="lightgrey")

msimilarity<-fsSimilarityMatrix(mlist, threshold = 0.1, method="Kuncheva")

plot(msimilarity, digits=2, col=rev(heat.colors(ncol(msimilarity))), key=NULL,
     main="System-wise", cex.axis=0.7,ylab="",xlab="")


matrixes<-list()
for (f in list.files(CCFg.folder)){
  mlist<-list(
    CCF=readRDS(file.path(CCFg.folder,f)),
    GLASSO=readRDS(file.path(GLASSOg.folder,f)),
    MI=readRDS(file.path(MIg.folder,f)),
    LARS=readRDS(file.path(LARSg.folder,f)),
    RF=readRDS(file.path(RFg.folder,f)),
    Distance=readRDS(distance.folder),
    EnsVoting=readRDS(file.path(EnsVotingg.folder,f)),
    EnsRanking=readRDS(file.path(EnsRankingg.folder,f))
  )
  print(f)
  matrixes[[length(matrixes)+1]]<-fsSimilarityMatrix(mlist, threshold = 0.1, method="Kuncheva")
}
res<-apply(simplify2array(matrixes), 1:2, mean)

fmt <- "%Y-%m-%d_%H%M%S"
day<-as.POSIXct("2017-08-02_000000",fmt)
mlist<-loadDay(day,CCFg.folder)
res<-fsSimilarityMatrix(mlist, threshold = 0.1,method="Kuncheva")
r<-res[order(rownames(res)), order(colnames(res))]
image(r,axes=FALSE)

mlist<-loadDay(day,CCF.folder)
res<-fsSimilarityMatrix(mlist, threshold = 0.1,method="Kuncheva")
r<-res[order(rownames(res)), order(colnames(res))]
image(r,axes=FALSE)
```



```{r create_drift}
maxlag<-3
CCF.folder <- file.path(dir,"fs",length(series),"CCF",36,maxlag)
MI.folder <- file.path(dir,"fs",length(series),"MI",36,maxlag)
GLASSO.folder <- file.path(dir,"fs",length(series),"GLASSOloc",36,maxlag,0.3)
LARS.folder <- file.path(dir,"fs",length(series),"LARS",36,maxlag)
RF.folder <- file.path(dir,"fs",length(series),"RF",36,maxlag)
EnsVoting.folder <- file.path(dir,"fs",length(series),"EnsVoting",36,maxlag,0.1)
EnsRanking.folder <- file.path(dir,"fs",length(series),"EnsRanking",36,maxlag,0.1)

EnsVoting.folder.drift <- file.path(dir,"fs",length(series),"EnsVotingdrift",36,maxlag,0.1)
EnsRanking.folder.drift <- file.path(dir,"fs",length(series),"EnsRankingdrift",36,maxlag,0.1)
SMOOTH_SIZE <- 6
prev <- list()
fold<-EnsRanking.folder
fold.drift <- EnsRanking.folder.drift
if (!file.exists(fold.drift)) dir.create(fold.drift, recursive = T)
p<-NULL
pOrig<-NULL
for (f in list.files(fold)){
  fs <- readRDS(file.path(fold,f))
  prev[[length(prev)+1]]<-fs
  if (length(prev)>SMOOTH_SIZE) prev[[1]] <- NULL
  if  (length(prev)==1){
    fs.drift <- fs
  }else{
    fs.drift <-apply(simplify2array(prev), 1:2, mean)
  }
  if (length(prev)>1) print(paste(f," ",fsSimilarity(p,fs.drift,cutoff=T, threshold = 0.1)," ",fsSimilarity(pOrig,fs,cutoff=T, threshold = 0.1)))
  p<-fs.drift
  pOrig<-fs
  saveRDS(fs.drift,file.path(fold.drift,f))
}

```

```{r create_ensemble}
maxlag<-3
fs.distance.global <- readRDS(file.path(dir,"fs",length(series),"distance",20160,maxlag,"2017-10-08_000000.rds"))
fs.CCF.global <- readRDS(file.path(dir,"fs",length(series),"CCF",20160,maxlag,"2017-10-08_000000.rds"))
fs.GLASSO.global <- readRDS(file.path(dir,"fs",length(series),"GLASSOloc",20160,maxlag,0.3,"2017-10-08_000000.rds"))
fs.MI.global <- readRDS(file.path(dir,"fs",length(series),"MI",4032,maxlag,"2017-08-13_000000.rds"))
fs.LARS.global <- readRDS(file.path(dir,"fs",length(series),"LARS",20160,maxlag,"2017-10-08_000000.rds"))
fs.RF.global <- readRDS(file.path(dir,"fs",length(series),"RF",20160,maxlag,"2017-10-08_000000.rds"))

mlist <- list(Distance = fs.distance.global,
              CCF = fs.CCF.global,
              GLASSO = fs.GLASSO.global,
              MI = fs.MI.global,
              LARS = fs.LARS.global,
              RF = fs.RF.global)

th<-0.1
plot(fs.CCF.global, col=rev(heat.colors(10)), key=NULL, main="FS")
plot(cutoff(fs.CCF.global,th), col=rev(heat.colors(10)), key=NULL, main="FS")
plot(cutoff(fs.LARS.global,th), col=rev(heat.colors(10)), key=NULL, main="FS")
mlist[["EnsembleRank"]] <- fsMTS::fsEnsemble(mlist, threshold = th, method="ranking")
mlist[["EnsembleMajV"]] <- fsMTS::fsEnsemble(mlist, threshold = th, method="majority")
(msimilarity <- fsSimilarityMatrix(mlist,threshold = th, method="Hamming"))
colnames(mlist[["EnsembleRank"]])<-colnames(mlist[["EnsembleMajV"]])
rownames(mlist[["EnsembleRank"]])<-rownames(mlist[["EnsembleMajV"]])
  
plot(mlist[["EnsembleMajV"]], col=rev(heat.colors(10)), key=NULL, main="FS")
val<-fsSimilarity(mlist[["EnsembleRank"]],mlist[["EnsembleMajV"]], method="Kuncheva")
fsMTS::fsSparsity(mlist[["EnsembleRank"]])
fsMTS::fsSparsity(mlist[["EnsembleMajV"]])
dir.create(file.path(dir,"fs",length(series),"EnsVoting",20160,maxlag,th), recursive = T)
dir.create(file.path(dir,"fs",length(series),"EnsRanking",20160,maxlag,th), recursive = T)
saveRDS(mlist[["EnsembleMajV"]], file.path(dir,"fs",length(series),"EnsVoting",20160,maxlag,th,"2017-10-08_000000.rds"))
saveRDS(mlist[["EnsembleRank"]], file.path(dir,"fs",length(series),"EnsRanking",20160,maxlag,th,"2017-10-08_000000.rds"))

maxlag<-3
CCFg.folder <- file.path(dir,"fs",length(series),"CCFg",36,maxlag)
MIg.folder <- file.path(dir,"fs",length(series),"MIg",36,maxlag)
GLASSOg.folder <- file.path(dir,"fs",length(series),"GLASSOlocg",36,maxlag,0.3)
LARSg.folder <- file.path(dir,"fs",length(series),"LARSg",36,maxlag)
RFg.folder <- file.path(dir,"fs",length(series),"RFg",36,maxlag)

EnsVotingg.folder <- file.path(dir,"fs",length(series),"EnsVotingg",36,maxlag,th)
dir.create(EnsVotingg.folder, recursive = T)
EnsRankingg.folder <- file.path(dir,"fs",length(series),"EnsRankingg",36,maxlag,th)
dir.create(EnsRankingg.folder, recursive = T)

for (f in list.files(CCFg.folder)){
  fs.CCF.daytime <- readRDS(file.path(CCFg.folder,f))
  fs.GLASSO.daytime <- readRDS(file.path(GLASSOg.folder,f))
  fs.MI.daytime <- readRDS(file.path(MIg.folder,f))
  fs.LARS.daytime <- readRDS(file.path(LARSg.folder,f))
  fs.RF.daytime <- readRDS(file.path(RFg.folder,f))
  mlist <- list(Distance = fs.distance.global,
              CCF = fs.CCF.daytime,
              GLASSO = fs.GLASSO.daytime,
              MI = fs.MI.daytime,
              LARS = fs.LARS.daytime,
              RF = fs.RF.daytime)
  EnsembleRank <- fsMTS::fsEnsemble(mlist, threshold = th, method="ranking")
  EnsembleMajV <- fsMTS::fsEnsemble(mlist, threshold = th, method="majority")
  colnames(EnsembleRank)<-colnames(EnsembleMajV)
  rownames(EnsembleRank)<-rownames(EnsembleMajV)
  saveRDS(EnsembleMajV,file.path(EnsVotingg.folder,f))
  saveRDS(EnsembleRank,file.path(EnsRankingg.folder,f))
  print(paste(f,"Sparsity",fsMTS::fsSparsity(EnsembleMajV)))
}



CCF.folder <- file.path(dir,"fs",length(series),"CCF",36,maxlag)
MI.folder <- file.path(dir,"fs",length(series),"MI",36,maxlag)
GLASSO.folder <- file.path(dir,"fs",length(series),"GLASSOloc",36,maxlag,0.3)
LARS.folder <- file.path(dir,"fs",length(series),"LARS",36,maxlag)
RF.folder <- file.path(dir,"fs",length(series),"RF",36,maxlag)

EnsVoting.folder <- file.path(dir,"fs",length(series),"EnsVoting",36,maxlag,th)
dir.create(EnsVoting.folder, recursive = T)
EnsRanking.folder <- file.path(dir,"fs",length(series),"EnsRanking",36,maxlag,th)
dir.create(EnsRanking.folder, recursive = T)

for (f in list.files(CCF.folder)){
  fs.CCF.dynamic <- readRDS(file.path(CCF.folder,f))
  fs.GLASSO.dynamic <- readRDS(file.path(GLASSO.folder,f))
  fs.MI.dynamic <- readRDS(file.path(MI.folder,f))
  fs.LARS.dynamic <- readRDS(file.path(LARS.folder,f))
  fs.RF.dynamic <- readRDS(file.path(RF.folder,f))
  mlist <- list(Distance = fs.distance.global,
              CCF = fs.CCF.dynamic,
              GLASSO = fs.GLASSO.dynamic,
              MI = fs.MI.dynamic,
              LARS = fs.LARS.dynamic,
              RF = fs.RF.dynamic)
  EnsembleRank <- fsMTS::fsEnsemble(mlist, threshold = th, method="ranking")
  EnsembleMajV <- fsMTS::fsEnsemble(mlist, threshold = th, method="majority")
  colnames(EnsembleRank)<-colnames(EnsembleMajV)
  rownames(EnsembleRank)<-rownames(EnsembleMajV)
  saveRDS(EnsembleMajV,file.path(EnsVoting.folder,f))
  saveRDS(EnsembleRank,file.path(EnsRanking.folder,f))
  print(paste(f,"Sparsity",fsMTS::fsSparsity(EnsembleMajV)))
}

```

```{r complexity}
install.packages("graph")
require(needs)
needs(BiocManager)
BiocManager::install("RBGL")
needs(QuACN)
needs(Rgraphviz)
set.seed(123)
g <- randomEGraph(as.character(1:10), 0.6)
offdiagonal(g)


convertToGraph<-function(fs){
  mEmpty <- matrix(0, nrow=nrow(fs),ncol=ncol(fs))
  adjM<-cbind(fs,mEmpty,mEmpty)
  adjM<-adjM+t(adjM)
  adjM[adjM>0]<-1
  colnames(adjM)<-rownames(adjM)
  g<-as(adjM,"graphNEL")
  return(g)
}

for (f in c(distance.folder,CCF.global, GLASSO.global, MI.global,LARS.global,RF.global,EnsVoting.global,EnsRanking.global)){
  print(paste(f,offdiagonal(convertToGraph(cutoff(readRDS(f),threshold=0.1)))))
}

options(pillar.sigfig = 4)

res<-list()
for (fold in c(CCFg.folder,MIg.folder,GLASSOg.folder,LARSg.folder,RFg.folder,EnsVotingg.folder,EnsRankingg.folder)){
  for (f in list.files(fold)){
    mFS=readRDS(file.path(fold,f))
    m<-cutoff(mFS,threshold=0.1)
    g<-convertToGraph(m)
    val <- offdiagonal(g)
    print(paste(fold,f,val))
    res[[length(res)+1]]<-list(folder=fold,file=f,odc=val)
  }
}
all<-bind_rows(res)
all%>%group_by(folder)%>%summarise(mean.odc = mean(odc))



res<-list()
for (fold in c(
CCF.folder,MI.folder,GLASSO.folder,LARS.folder,RF.folder,EnsVoting.folder,EnsRanking.folder,
CCF.folder.drift,MI.folder.drift,GLASSO.folder.drift,LARS.folder.drift,RF.folder.drift,EnsVoting.folder.drift,EnsRanking.folder.drift)){
  for (f in list.files(fold)){
    mFS=readRDS(file.path(fold,f))
    m<-cutoff(mFS,threshold=0.1)
    g<-convertToGraph(m)
    val <- offdiagonal(g)
    print(paste(fold,f,val))
    res[[length(res)+1]]<-list(folder=fold,file=f,odc=val)
  }
}
all<-bind_rows(res)
all%>%group_by(folder)%>%summarise(mean.odc = mean(odc))
```
